version: '3'

services:
        db:
                image: mongo
                restart: unless-stopped
                volumes:
                        - /home/raul/mongo:/data/db
                ports:
                        - '27017:27017'
                networks:
                        - paponet
        app:
                container_name: batepapo-nodejs
                build: .
                command: node index.js
                volumes:
                        - .:/code
                ports:
                        - '3000:3000'
                depends_on:
                        - db
                networks:
                        - paponet
networks:
        paponet:
                driver: bridge
                
